part 'models.dart';

/// This file was generated by xata-client OpenAPI code-gen 

typedef APIKeyName = String;
typedef BranchName = String;
enum TYPE {bool,int,float,string,text,email,multiple,link,object,}
typedef ColumnName = String;
typedef ColumnsFilter = List<String>;
typedef DBBranchName = String;
typedef DBName = String;
typedef DateTime = String;
typedef InviteID = String;
typedef InviteKey = String;
typedef RecordID = String;
enum Role {owner,maintainer,}
enum SortOrder {asc,desc,}
typedef TableName = String;
typedef UserID = String;
typedef WorkspaceID = String;
